# ═══════════════════════════════════════════════════════════
#  ConfigMap de PRODUCTION
# ═══════════════════════════════════════════════════════════
apiVersion: v1
kind: ConfigMap
metadata:
  name: juribook-common-config
  namespace: juribook-production
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  AUTH_SERVICE_BASE_URL: "http://auth-service:8081"
  LAWYER_SERVICE_BASE_URL: "http://lawyer-service:8082"
  BOOKING_SERVICE_BASE_URL: "http://booking-service:8083"
  NOTIFICATION_SERVICE_BASE_URL: "http://notification-service:8084"
  AUDIT_SERVICE_BASE_URL: "http://audit-service:8085"

  AUTH_SERVICE_URL: "http://auth-service:8081"
  LAWYER_SERVICE_URL: "http://lawyer-service:8082"
  BOOKING_SERVICE_URL: "http://booking-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
  AUDIT_SERVICE_URL: "http://audit-service:8085"

  # ⚠️ MailHog reste utilisé ici comme en staging (portfolio) —
  # avant une vraie mise en production, remplacer par un vrai
  # fournisseur SMTP (Sendgrid, Scaleway Transactional Email...).
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
